<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>MemoryCleaner</AssemblyName>
    <RootNamespace>MemoryCleaner</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\tray.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <InvariantGlobalization>false</InvariantGlobalization>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <StripSymbols>false</StripSymbols>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="Assets\tray.ico" LogicalName="MemoryCleaner.Assets.tray.ico" />
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
  </ItemGroup>

  <Target Name="KeepPublishDirectorySingleExe" AfterTargets="Publish">
    <ItemGroup>
      <FilesToRemoveAfterPublish Include="$(PublishDir)MemoryCleaner.pdb" />
      <FilesToRemoveAfterPublish Include="$(PublishDir)*.pdb" />
      <FoldersToRemoveAfterPublish Include="$(PublishDir)Assets" />
    </ItemGroup>
    <Delete Files="@(FilesToRemoveAfterPublish)" TreatErrorsAsWarnings="true" />
    <RemoveDir Directories="@(FoldersToRemoveAfterPublish)" />
  </Target>
</Project>
